name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Run Docker Compose
      run: docker compose up -d --build

    - name: Wait for the application to be ready
      run: |
        echo "Waiting for the app to be ready..."
        sleep 15
        curl --fail http://localhost:5000/data

    - name: Verify data in PostgreSQL
      run: |
        docker exec <postgres_container_name> psql -U user -d mydatabase -c "SELECT * FROM test_table;"

    - name: Stop and clean up
      run: docker-compose down
